# Generated by Django 3.1 on 2020-09-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='p_description',
            new_name='post_description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='p_title',
            new_name='post_title',
        ),
    ]
