# Generated by Django 3.1 on 2020-09-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200828_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='imgae',
            new_name='image',
        ),
    ]
