# Generated by Django 3.1 on 2020-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=400)),
                ('Description', models.ImageField(upload_to='donor/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('raised_amount', models.FloatField()),
                ('goal_amount', models.FloatField()),
            ],
        ),
    ]
