# Generated by Django 3.1 on 2020-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20200918_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='goal_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='raised_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
