# Generated by Django 3.1 on 2020-10-19 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20200918_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
