# Generated by Django 3.1 on 2020-09-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='bkash_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='donate',
            name='address',
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
